import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  patterns: [{ type: 'autogenerated', dirName: 'patterns' }],
  dataStructure: [{ type: 'autogenerated', dirName: 'dataStructure' }],
  kotlin: [{ type: 'autogenerated', dirName: 'kotlin' }],
  python: [{ type: 'autogenerated', dirName: 'python' }],
  lua: [{ type: 'autogenerated', dirName: 'lua' }],
  //====================================utils
  git: [{ type: 'autogenerated', dirName: 'utils/git' }],
  svn: [{ type: 'autogenerated', dirName: 'utils/svn' }],
  vim: [{ type: 'autogenerated', dirName: 'utils/vim' }],
  neovim: [{ type: 'autogenerated', dirName: 'utils/neovim' }],
  jmeter: [{ type: 'autogenerated', dirName: 'utils/jmeter' }],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
