/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "jaspernote",
  "tagline": "jasper learn note",
  "favicon": "img/jaspernote-logo.svg",
  "url": "https://your-docusaurus-site.example.com",
  "baseUrl": "/jaspernote/",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true,
      "siteStorageNamespacing": true,
      "fasterByDefault": true,
      "mdx1CompatDisabledByDefault": true
    },
    "experimental_vcs": {},
    "experimental_router": "browser",
    "faster": {
      "swcJsLoader": true,
      "swcJsMinimizer": true,
      "swcHtmlMinimizer": true,
      "lightningCssMinimizer": true,
      "mdxCrossCompilerCache": true,
      "rspackBundler": true,
      "rspackPersistentCache": true,
      "ssgWorkerThreads": true,
      "gitEagerVcs": true
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "emoji": true,
    "mdx1Compat": {
      "comments": false,
      "admonitions": false,
      "headingIds": false
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  },
  "organizationName": "jaspercliff",
  "projectName": "jaspernote",
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./configs/sidebars.ts",
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/",
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/jaspernote-logo.svg",
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "navbar": {
      "title": "jaspernote",
      "logo": {
        "alt": "jaspernote logo",
        "src": "img/jaspernote-logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "patterns",
          "position": "left",
          "label": "设计模式"
        },
        {
          "type": "docSidebar",
          "sidebarId": "dataStructure",
          "position": "left",
          "label": "数据结构"
        },
        {
          "type": "dropdown",
          "label": "java",
          "position": "left",
          "items": [
            {
              "label": "开发工具",
              "to": "/docs/java/devTools",
              "sidebarId": "devTools"
            },
            {
              "label": "foundation",
              "to": "/docs/java/basic",
              "sidebarId": "javaBasic"
            },
            {
              "label": "framework",
              "to": "/docs/java/framework",
              "sidebarId": "framework"
            }
          ]
        },
        {
          "type": "docSidebar",
          "sidebarId": "kotlin",
          "position": "left",
          "label": "kotlin"
        },
        {
          "type": "docSidebar",
          "sidebarId": "python",
          "position": "left",
          "label": "python"
        },
        {
          "type": "docSidebar",
          "sidebarId": "lua",
          "position": "left",
          "label": "lua"
        },
        {
          "type": "dropdown",
          "label": "front",
          "position": "left",
          "items": [
            {
              "label": "html",
              "to": "/docs/front/html",
              "sidebarId": "html"
            },
            {
              "label": "css",
              "to": "/docs/front/css",
              "sidebarId": "css"
            },
            {
              "label": "js",
              "to": "/docs/front/js",
              "sidebarId": "js"
            },
            {
              "label": "jquery",
              "to": "/docs/front/jquery",
              "sidebarId": "jquery"
            },
            {
              "label": "vitepress",
              "to": "/docs/front/vitepress",
              "sidebarId": "vitepress"
            },
            {
              "label": "docusaurus",
              "to": "/docs/front/docusaurus",
              "sidebarId": "docusaurus"
            },
            {
              "label": "vue",
              "to": "/docs/front/vue",
              "sidebarId": "vue"
            },
            {
              "label": "react",
              "to": "/docs/front/react",
              "sidebarId": "react"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "dataLayer",
          "position": "left",
          "items": [
            {
              "label": "关系型数据库",
              "to": "/docs/dataLayer/relational/",
              "sidebarId": "relational"
            },
            {
              "label": "分布式数据库",
              "to": "/docs/dataLayer/distributed/",
              "sidebarId": "distributed"
            },
            {
              "label": "NoSQL",
              "to": "/docs/dataLayer/nosql/",
              "sidebarId": "nosql"
            },
            {
              "label": "连接池",
              "to": "/docs/dataLayer/connectPool/",
              "sidebarId": "connectPool"
            },
            {
              "label": "分库分表",
              "to": "/docs/dataLayer/sharding/",
              "sidebarId": "sharding"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "system design",
          "position": "left",
          "items": [
            {
              "label": "operating system",
              "to": "/docs/infrastructure/os",
              "sidebarId": "os"
            },
            {
              "label": "system design",
              "to": "/docs/infrastructure/design",
              "sidebarId": "design"
            },
            {
              "label": "devops",
              "to": "/docs/infrastructure/devops",
              "sidebarId": "devops"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "utils",
          "position": "left",
          "items": [
            {
              "label": "git",
              "to": "/docs/utils/git",
              "sidebarId": "dataStructure"
            },
            {
              "label": "svn",
              "to": "/docs/utils/svn",
              "sidebarId": "svn"
            },
            {
              "label": "vim",
              "to": "/docs/utils/vim",
              "sidebarId": "vim"
            },
            {
              "label": "neovim",
              "to": "/docs/utils/neovim",
              "sidebarId": "neovim"
            },
            {
              "label": "jmeter",
              "to": "/docs/utils/jmeter",
              "sidebarId": "jmeter"
            }
          ]
        },
        {
          "to": "/docs/tags",
          "label": "标签云",
          "position": "right"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "right"
        },
        {
          "href": "https://github.com/facebook/docusaurus",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Community",
          "items": [
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/docusaurus"
            },
            {
              "label": "Discord",
              "href": "https://discordapp.com/invite/docusaurus"
            },
            {
              "label": "X",
              "href": "https://x.com/docusaurus"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/facebook/docusaurus"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 My Project, Inc. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "java",
        "lua"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": true
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
